//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// GameEditor.rc에서 사용되고 있습니다.
//
#define IDD_ABOUTBOX                    100
#define IDD_FORMVIEW                    101
#define IDD_WORLDOBJ                    101
#define IDD_OBJDETAIL                   102
#define IDR_MAINFRAME                   128
#define IDR_GameEditorTYPE              130
#define IDD_DIALOG_ANIEDIT              312
#define IDD_COLLIDER_RECT               313
#define IDD_DIALOG_TILEMAP              315
#define IDD_DIALOG_OBJ_CREATE           318
#define IDD_DIALOG_COLLIDERCIRCLE       320
#define IDD_DIALOG_COLLIDER_OBB2D       322
#define IDD_DIALOG_COLLIDER_LINE        324
#define IDD_DIALOG_MESH2D               326
#define IDD_DIALOG_STATICMESH           328
#define IDD_DIALOG_CAMERA               330
#define IDD_DIALOG_SPRITE               332
#define IDD_DIALOG_COLLIDER_PIXEL       334
#define IDD_DIALOG_COLLIDER_POINT       336
#define IDD_DIALOG_UI_BAR               338
#define IDD_DIALOG_UI_CHECK             340
#define IDD_DIALOG_UI_BUTTON            342
#define IDD_DIALOG_RADIO                344
#define IDD_DIALOG_PANEL                346
#define IDD_DIALOG_UI_CONTROL           348
#define IDD_DIALOG_SLIDER               350
#define IDD_DIALOG_FONT                 352
#define IDD_DIALOG_RENDERER             354
#define IDD_DIALOG_UI_IMAGE             356
#define IDD_DIALOG_UI_TITLE             358
#define IDD_DIALOG_TAB                  360
#define IDD_DIALOG_UI_LIST              362
#define IDD_DIALOG_SOUND                364
#define IDC_TREE_COMPONENT              1000
#define IDC_EDIT1                       1001
#define IDC_EDIT_POSX                   1001
#define IDC_EDIT_TAG                    1001
#define IDC_EDIT_RADIUS                 1001
#define IDC_EDIT_POS_X                  1001
#define IDC_EDIT_START_X                1001
#define IDC_EDIT_CURRENT                1001
#define IDC_EDIT_TILE_SIZE_X            1001
#define IDC_EDIT_WIDTH                  1001
#define IDC_EDIT_POINT_X                1001
#define IDC_EDIT_DIR                    1001
#define IDC_EDIT_SOUND_ON               1001
#define IDC_EDIT_BUTTON_STATE           1001
#define IDC_EDIT2                       1002
#define IDC_EDIT_SCALEX                 1002
#define IDC_EDIT_RATE                   1002
#define IDC_EDIT_HEIGHT                 1002
#define IDC_EDIT_LEFT                   1002
#define IDC_EDIT_CENTER_X               1002
#define IDC_EDIT_POS_Y                  1002
#define IDC_EDIT_START_Y                1002
#define IDC_EDIT_ANGLE                  1002
#define IDC_EDIT_FRAME                  1002
#define IDC_EDIT_POINT_Y                1002
#define IDC_EDIT_PERCENT                1002
#define IDC_EDIT_SOUND_OFF              1002
#define IDC_EDIT_IMAGE_TYPE             1002
#define IDC_EDIT_SLIDER_TYPE            1002
#define IDC_EDIT_TEXT                   1002
#define IDC_EDIT_MAT_SHADER_INST_SIZE   1002
#define IDC_EDIT3                       1003
#define IDC_EDIT_ROTX                   1003
#define IDC_EDIT_TIME                   1003
#define IDC_EDIT_TOP                    1003
#define IDC_EDIT_CENTER_Y               1003
#define IDC_EDIT_POS_Z                  1003
#define IDC_EDIT_START_Z                1003
#define IDC_EDIT_TILE_SIZE_Y            1003
#define IDC_EDIT_POINT_Z                1003
#define IDC_EDIT_TEXTURE_ON             1003
#define IDC_EDIT_CONTROL_FRAME          1003
#define IDC_EDIT_FONT                   1003
#define IDC_EDIT_MAT_SHADERTYPE         1003
#define IDC_EDIT_FRAME_MAX              1003
#define IDC_EDIT4                       1004
#define IDC_EDIT_POSZ                   1004
#define IDC_EDIT_TEX_TAG                1004
#define IDC_EDIT_RIGHT                  1004
#define IDC_EDIT_CENTER_Z               1004
#define IDC_EDIT_AXIS_X_X               1004
#define IDC_EDIT_END_X                  1004
#define IDC_EDIT_SEQ_TIME               1004
#define IDC_EDIT_TILE_CNT_X             1004
#define IDC_EDIT_UIPOINT_X              1004
#define IDC_EDIT_TEXTURE_OFF            1004
#define IDC_EDIT_CONTROL_START_X        1004
#define IDC_EDIT_COUNT                  1004
#define IDC_EDIT5                       1005
#define IDC_EDIT_SCALEZ                 1005
#define IDC_EDIT_BOT                    1005
#define IDC_EDIT_AXIS_X_Y               1005
#define IDC_EDIT_END_Y                  1005
#define IDC_EDIT_TILE_CNT_Y             1005
#define IDC_EDIT_UIPOINT_Y              1005
#define IDC_EDIT_TEXTURE_PRESS          1005
#define IDC_EDIT_SOUND_RADIO_ON         1005
#define IDC_EDIT_CONTROL_START_Y        1005
#define IDC_EDIT_SIZE                   1005
#define IDC_EDIT_MAT_LINE_TYPE          1005
#define IDC_EDIT_PLAY_RATE              1005
#define IDC_EDIT6                       1006
#define IDC_EDIT_ROTZ                   1006
#define IDC_EDIT_EXX                    1006
#define IDC_EDIT_AXIS_X_Z               1006
#define IDC_EDIT_END_Z                  1006
#define IDC_EDIT_TILE_TEXTURE           1006
#define IDC_EDIT_UIPOINT_Z              1006
#define IDC_EDIT_TEXTURE_DISABLE        1006
#define IDC_EDIT_CONTROL_END_X          1006
#define IDC_EDIT_MAT_REGISTER           1006
#define IDC_EDIT_SEQ_TIME2              1006
#define IDC_EDIT7                       1007
#define IDC_EDIT_POSY                   1007
#define IDC_EDIT_EXY                    1007
#define IDC_EDIT_AXIS_Y_X               1007
#define IDC_EDIT_COLOR_OFF_R            1007
#define IDC_EDIT_CONTROL_END_Y          1007
#define IDC_EDIT_TEXT_HEIGHT            1007
#define IDC_EDIT_MAT_SHADER_TYPE        1007
#define IDC_EDIT8                       1008
#define IDC_EDIT_SCALEY                 1008
#define IDC_EDIT_AXIS_Y_Y               1008
#define IDC_EDIT_COLOR_ON_R             1008
#define IDC_EDIT_CONTROL_SIZE_X         1008
#define IDC_EDIT_OPACITY                1008
#define IDC_EDIT_MIN_X                  1008
#define IDC_EDIT9                       1009
#define IDC_EDIT_ROTY                   1009
#define IDC_EDIT_AXIS_Y_Z               1009
#define IDC_EDIT_COLOR_PRESS_R          1009
#define IDC_EDIT_CONTROL_SIZE_Y         1009
#define IDC_EDIT_SHADOW_OPACITY         1009
#define IDC_EDIT_MAX_X                  1009
#define IDC_EDIT_AXIS_Z_X               1010
#define IDC_EDIT_COLOR_DISABLE_R        1010
#define IDC_EDIT_MIN_Y                  1010
#define IDC_TREE_CONTROL                1011
#define IDC_EDIT_AXIS_Z_Y               1011
#define IDC_EDIT_COLOR_OFF_G            1011
#define IDC_EDIT_MAX_Y                  1011
#define IDC_BUTTON_TEXTURE_LOAD         1012
#define IDC_EDIT_AXIS_Z_Z               1012
#define IDC_EDIT_MIN_Z                  1012
#define IDC_LIST_SEQUENCE               1013
#define IDC_EDIT_LENGTH_X               1013
#define IDC_EDIT_COLOR_ON_G             1013
#define IDC_EDIT_MAX_Z                  1013
#define IDC_BUTTON_ADD_SEQUENCE         1014
#define IDC_EDIT_COL_RADIUS             1014
#define IDC_EDIT_LENGTH_Y               1014
#define IDC_EDIT_COLOR_PRESS_G          1014
#define IDC_EDIT_INST_COUNT             1014
#define IDC_BUTTON_SAVE_SEQUENCE        1015
#define IDC_EDIT_COL_EXTENT_X           1015
#define IDC_EDIT_LENGTH_Z               1015
#define IDC_EDIT_COLOR_DISABLE_G        1015
#define IDC_EDIT_MESH_MAT_SHADER_DESC_SIZE 1015
#define IDC_BUTTON_LOAD_SEQUENCE        1016
#define IDC_BUTTON1                     1016
#define IDC_EDIT_COL_EXTENTY            1016
#define IDC_BUTTON_CREATE               1016
#define IDC_BUTTON_SAVE                 1016
#define IDC_EDIT_DIST                   1016
#define IDC_EDIT_COLOR_OFF_B            1016
#define IDC_EDIT_MESH_MAT_SHADER_INST_SIZE 1016
#define IDC_BUTTON2                     1017
#define IDC_BUTTON_LOAD                 1017
#define IDC_EDIT_TYPE                   1017
#define IDC_EDIT_COLOR_ON_B             1017
#define IDC_EDIT_MESH_MAT_SHADERTYPE    1017
#define IDC_BUTTON_OPEN_TILEMAP         1017
#define IDC_TAB1                        1018
#define IDC_BUTTON_CREATE_TILE          1018
#define IDC_EDIT_COLOR_PRESS_B          1018
#define IDC_EDIT_MESH_MAT_LINK_TYPE     1018
#define IDC_COMBO_TILE                  1019
#define IDC_EDIT_COLOR_DISABLE_B        1019
#define IDC_EDIT_MESH_MAT_REGISTER      1019
#define IDC_COMBO_TILE_INDEX            1020
#define IDC_LIST_PROTO                  1020
#define IDC_EDIT_COLOR_OFF_A            1020
#define IDC_EDIT_MESH_MAT_SHADER_TYPE   1020
#define IDC_COMBO_TILE_OPTION           1021
#define IDC_EDIT_COLOR_ON_A             1021
#define IDC_EDIT_MESH_MAT_TEX           1021
#define IDC_CHECK_MODIFY                1022
#define IDC_EDIT_COLOR_PRESS_A          1022
#define IDC_EDIT_MESH_NAME              1022
#define IDC_LIST_SEQ                    1023
#define IDC_EDIT_COLOR_DISABLE_A        1023
#define IDC_EDIT_MAT_TEX                1023
#define IDC_CHECK_LOOP                  1024
#define IDC_EDIT_SCROLL                 1024
#define IDC_EDIT_MESH_MAT_NAME          1024
#define IDC_CHECK_ARRAYTEX              1025
#define IDC_EDIT_SCROLL2                1025
#define IDC_EDIT_MESH_SHADER_NAME       1025
#define IDC_CHECK_STOP                  1026
#define IDC_BUTTON_LOAD_TILE_TEXTURE    1026
#define IDC_EDIT_SLIDER_START_X         1026
#define IDC_EDIT_MAT_NAME               1026
#define IDC_EDIT_SLIDER_START_Y         1027
#define IDC_EDIT_SHADER_NAME            1027
#define IDC_BYTE_SIZE                   1028
#define IDC_EDIT_SLIDER_START_Z         1028
#define IDC_EDIT_LAYER                  1028
#define IDC_PIXEL_COL_TYPE              1029
#define IDC_CHECK1                      1029
#define IDC_EDIT_SLIDER_PERCENT         1029
#define IDC_EDIT_LAYER2                 1029
#define IDC_EDIT_SCENE                  1029
#define IDC_COLOR_R                     1030
#define IDC_LIST_CALLBACK_OFF           1030
#define IDC_CHECK_SHADOW_ALPHA          1030
#define IDC_COLOR_G                     1031
#define IDC_LIST_CALLBACK_ON            1031
#define IDC_CHECK_SHADOW                1031
#define IDC_COLOR_B                     1032
#define IDC_LIST_BOX_CALLBACK_OFF       1032
#define IDC_COMBO_CALLBACK_OFF          1032
#define IDC_COLOR_A                     1033
#define IDC_LIST_BOX_CALLBACK_ON        1033
#define IDC_COMBO_CALLBACK_ON           1033
#define IDC_COMBO_BUTTONS               1033
#define IDC_CHECKCOLOR_R                1034
#define IDC_COMBO_CALLBACK_PRESS        1034
#define IDC_CHECKCOLOR_G                1035
#define IDC_COMBO_CALLBACK_DISABLE      1035
#define IDC_COMBO_CALLBACK_RADIO_ON     1035
#define IDC_RADIO_LEFT                  1035
#define IDC_CHECKCOLOR_B                1036
#define IDC_COMBO_BTN_CALLBACK_OFF      1036
#define IDC_RADIO_CENTER                1036
#define IDC_CHECKCOLOR_A                1037
#define IDC_COMBO_BTN_CALLBACK_ON       1037
#define IDC_RADIO_RIGHT                 1037
#define IDC_PIXEL_RECT_TOP              1038
#define IDC_COMBO_BTN_CALLBACK_PRESS    1038
#define IDC_RADIO_TOP                   1038
#define IDC_PIXEL_RECT_LEFT             1039
#define IDC_COMBO_BTN_CALLBACK_DISABLE  1039
#define IDC_RADIO_MID                   1039
#define IDC_PIXEL_RECT_RIGHT            1040
#define IDC_RADIO_BOT                   1040
#define IDC_PIXEL_RECT_BOTTOM           1041
#define IDC_EDIT_OFFSET_X               1041
#define IDC_EDIT_OFFSET_Y               1042
#define IDC_EDIT_OFFSET_Z               1043
#define IDC_CHECK_ALPHA                 1044
#define IDC_EDIT_COLOR_R                1045
#define IDC_EDIT_COLOR_G                1046
#define IDC_EDIT_COLOR_B                1047
#define IDC_EDIT_SHADOW_COLOR_R         1048
#define IDC_EDIT_SHADOW_COLOR_G         1049
#define IDC_EDIT_SHADOW_COLOR_B         1050
#define IDC_EDIT_TEXT_TOP               1051
#define IDC_EDIT_TEXT_LEFT              1052
#define IDC_COMBO_MAT_TEX_INFO          1052
#define IDC_EDIT_TEXT_RIGHT             1053
#define IDC_COMBO_MESH_TEXTUREINFO      1053
#define IDC_EDIT_TEXT_BOTTOM            1054
#define IDC_EDIT_MAT_SHADER_DESC_SIZE   1054
#define IDC_CHECK_PUSH                  1055
#define IDC_LIST1                       1056
#define IDC_EDIT_NAME                   1057
#define IDC_EDIT_SOUND_TYPE             1058
#define IDC_BUTTON_LOAD_SOUND           1059
#define IDC_CHECK_INST                  1060
#define IDC_BUTTON_LOAD_MESH_TEX        1061
#define IDC_BUTTON_LOAD_TEX             1062
#define ID_32771                        32771
#define ID_32772                        32772
#define ID_32773                        32773
#define ID_32774                        32774
#define ID_OBJ_CREATE                   32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        366
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1062
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
